
import { pactWith } from 'jest-pact';
import { Matchers } from '@pact-foundation/pact';
import { financialServiceClient } from './financial-service-client';

pactWith({ consumer: 'FinancialServiceConsumer', provider: 'FinancialServiceProvider' }, provider => {
  let client;

  beforeEach(() => {
    client = financialServiceClient(provider.mockService.baseUrl)
  });

  describe('get financial defination service', () => {
    beforeEach(() => 
      provider.addInteraction({
        state: "Given Financial loan amount",
        uponReceiving: 'A request to Financial service',
        willRespondWith: {
          status: 200,
          body: Matchers.like({
            applicationId: "3d3a1e01-5832-4ba1-9bd9-c767c737afd9",
            quoteCreated: "2023-03-09T23:58:23.129627Z",
            amountRequested: 10000.0,
            productQuotes: [
              {
                productId: 8,
                name: "1 Year Loan",
                description: "Variable rate 1 year loan",
                term: 12,
                loanAmount: 10245.0,
                annualRate: 12.69,
                financierRate: 12.69,
                rateType: "Variable",
                repayment: 913.57,
                repaymentFrequency: "Monthly",
                totalRepaid: 10962.84,
                effectiveRate: 17.35,
                asicComparisonRate: 14.4,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 41,
                name: "2 Year Loan Product",
                description: "Variable rate 2 year loan.",
                term: 24,
                loanAmount: 10245.0,
                annualRate: 12.69,
                financierRate: 12.69,
                rateType: "Variable",
                repayment: 485.58,
                repaymentFrequency: "Monthly",
                totalRepaid: 11653.92,
                effectiveRate: 15.1,
                asicComparisonRate: 14.4,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 111,
                name: "3 Year Loan",
                description: "Fixed rate 3 year loan",
                term: 36,
                loanAmount: 10245.0,
                annualRate: 12.99,
                financierRate: 12.99,
                rateType: "Fixed",
                repayment: 345.15,
                repaymentFrequency: "Monthly",
                totalRepaid: 12425.4,
                effectiveRate: 14.67,
                asicComparisonRate: 14.67,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 112,
                name: "4 Year Loan",
                description: "Fixed rate 4 year loan",
                term: 48,
                loanAmount: 10245.0,
                annualRate: 13.19,
                financierRate: 13.19,
                rateType: "Fixed",
                repayment: 275.81,
                repaymentFrequency: "Monthly",
                totalRepaid: 13238.88,
                effectiveRate: 14.49,
                asicComparisonRate: 14.23,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 113,
                name: "5 Year Loan",
                description: "Fixed rate 5 year loan",
                term: 60,
                loanAmount: 10245.0,
                annualRate: 13.19,
                financierRate: 13.19,
                rateType: "Fixed",
                repayment: 234.1,
                repaymentFrequency: "Monthly",
                totalRepaid: 14046.0,
                effectiveRate: 14.23,
                asicComparisonRate: 14.23,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 60,
                name: "Warehouse Loan 72 Month Personal and Renewable",
                description: "72 Month Personal and Renewable Warehouse Loan",
                term: 72,
                loanAmount: 10245.0,
                annualRate: 13.89,
                financierRate: 13.89,
                rateType: "Fixed",
                repayment: 210.5,
                repaymentFrequency: "Monthly",
                totalRepaid: 15156.0,
                effectiveRate: 14.84,
                asicComparisonRate: 14.93,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 62,
                name: "Warehouse Loan 84 Month Personal and Renewable",
                description: "84 Month Personal and Renewable Warehouse Loan",
                term: 84,
                loanAmount: 10245.0,
                annualRate: 13.89,
                financierRate: 13.89,
                rateType: "Fixed",
                repayment: 191.37,
                repaymentFrequency: "Monthly",
                totalRepaid: 16075.08,
                effectiveRate: 14.67,
                asicComparisonRate: 14.93,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
            ],
            additionalInformation: {
              loanAmount: "1000000",
              isAuthorizedToShowDetailedQuote: "False",
              AppRequiresFSRConsideration: "true",
              isCaravanBroker: "True",
              showIncomeVerificationType: "False",
              canUseFlex: "false",
              canUseAutoPremiumBucket: "true",
            },
          }),
        },
        withRequest: {
          method: 'GET',
          path: '/financequote/application/3d3a1e01-5832-4ba1-9bd9-c767c737afd9/quote',
          query: { loanAmount: '10000' },
        },
      })
    );

    it('returns server health', () => // implicit return again
      client.getLoanAmount('3d3a1e01-5832-4ba1-9bd9-c767c737afd9', '10000').then(definition => {
        expect(definition).toEqual({
            applicationId: "3d3a1e01-5832-4ba1-9bd9-c767c737afd9",
            quoteCreated: "2023-03-09T23:58:23.129627Z",
            amountRequested: 10000.0,
            productQuotes: [
              {
                productId: 8,
                name: "1 Year Loan",
                description: "Variable rate 1 year loan",
                term: 12,
                loanAmount: 10245.0,
                annualRate: 12.69,
                financierRate: 12.69,
                rateType: "Variable",
                repayment: 913.57,
                repaymentFrequency: "Monthly",
                totalRepaid: 10962.84,
                effectiveRate: 17.35,
                asicComparisonRate: 14.4,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 41,
                name: "2 Year Loan Product",
                description: "Variable rate 2 year loan.",
                term: 24,
                loanAmount: 10245.0,
                annualRate: 12.69,
                financierRate: 12.69,
                rateType: "Variable",
                repayment: 485.58,
                repaymentFrequency: "Monthly",
                totalRepaid: 11653.92,
                effectiveRate: 15.1,
                asicComparisonRate: 14.4,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 111,
                name: "3 Year Loan",
                description: "Fixed rate 3 year loan",
                term: 36,
                loanAmount: 10245.0,
                annualRate: 12.99,
                financierRate: 12.99,
                rateType: "Fixed",
                repayment: 345.15,
                repaymentFrequency: "Monthly",
                totalRepaid: 12425.4,
                effectiveRate: 14.67,
                asicComparisonRate: 14.67,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 112,
                name: "4 Year Loan",
                description: "Fixed rate 4 year loan",
                term: 48,
                loanAmount: 10245.0,
                annualRate: 13.19,
                financierRate: 13.19,
                rateType: "Fixed",
                repayment: 275.81,
                repaymentFrequency: "Monthly",
                totalRepaid: 13238.88,
                effectiveRate: 14.49,
                asicComparisonRate: 14.23,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 113,
                name: "5 Year Loan",
                description: "Fixed rate 5 year loan",
                term: 60,
                loanAmount: 10245.0,
                annualRate: 13.19,
                financierRate: 13.19,
                rateType: "Fixed",
                repayment: 234.1,
                repaymentFrequency: "Monthly",
                totalRepaid: 14046.0,
                effectiveRate: 14.23,
                asicComparisonRate: 14.23,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 60,
                name: "Warehouse Loan 72 Month Personal and Renewable",
                description: "72 Month Personal and Renewable Warehouse Loan",
                term: 72,
                loanAmount: 10245.0,
                annualRate: 13.89,
                financierRate: 13.89,
                rateType: "Fixed",
                repayment: 210.5,
                repaymentFrequency: "Monthly",
                totalRepaid: 15156.0,
                effectiveRate: 14.84,
                asicComparisonRate: 14.93,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
              {
                productId: 62,
                name: "Warehouse Loan 84 Month Personal and Renewable",
                description: "84 Month Personal and Renewable Warehouse Loan",
                term: 84,
                loanAmount: 10245.0,
                annualRate: 13.89,
                financierRate: 13.89,
                rateType: "Fixed",
                repayment: 191.37,
                repaymentFrequency: "Monthly",
                totalRepaid: 16075.08,
                effectiveRate: 14.67,
                asicComparisonRate: 14.93,
                upfrontFees: [
                  {
                    name: "Credit Assistance Fee",
                    amount: 245.0,
                    feeType: "CreditAssistanceFee",
                  },
                ],
                repaymentFees: [],
                customFees: [],
                balloonAmount: 0.0,
                balloonPercentage: 0.0,
                paymentSchedule: null,
                fullPaymentSchedule: null,
              },
            ],
            additionalInformation: {
              loanAmount: "1000000",
              isAuthorizedToShowDetailedQuote: "False",
              AppRequiresFSRConsideration: "true",
              isCaravanBroker: "True",
              showIncomeVerificationType: "False",
              canUseFlex: "false",
              canUseAutoPremiumBucket: "true",
            },
          });
      }));
  });
});
